### ISSUE TITLE
Error when using roblox-ts

### ISSUE THREAD

**Issue by notme1560** [vocksel/module-loader#12]
![image](https://user-images.githubusercontent.com/20008627/215235368-bd676016-b442-419b-9c0d-e7cdf14e2b69.png)
(Flipbook error, but I think the fix is within `module-loader`)

Occurs after Rojo syncs changes. There is discussion in the roblox-ts discord about the "invalid module access" error, it seems like it's related to the cacheless require-ing that the module loader does.

I think this line in Hoarcekat's source avoids the error by replacing `_G` in the loaded script: https://github.com/Kampfkarren/hoarcekat/blob/b7928ea9a640fe004f149b4ed8805780c065147a/src/Components/Preview.lua#L159

**Comment by vocksel** [comment]
Thanks for reporting this! Fixing this might be a tad tricky because I don't use roblox-ts, but I can at the very least take a stab at this sometime, bump the version, get it installed in flipbook, and you can let me know if it's resolved

**Comment by Milo123459** [comment]
Hey! Any updates on this / any way I can help out with this issue?
